# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: ''
author_name: Kappa
cloud_provider: netlify
ide_jetbrains: false
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: Janus
use_daisy_ui: true
use_eslint_prettier: true
use_github_actions: true
use_jest: true
use_playwright: true
use_tailwind: false

